/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import models.Empleado;
import com.google.gson.Gson;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

public class AltaEmpleado extends javax.swing.JFrame {

    public AltaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TFDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LbContrasena = new javax.swing.JLabel();
        TFDireccion = new javax.swing.JTextField();
        TFApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TFTelefono = new javax.swing.JTextField();
        TFEmail = new javax.swing.JTextField();
        TFUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PFContrasena = new javax.swing.JPasswordField();
        LbContrasena1 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        CBRol = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Alta Empleado");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("DNI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        jPanel1.add(TFDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 170, -1));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        LbContrasena.setText("Contraseña");
        jPanel1.add(LbContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(TFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 300, -1));
        jPanel1.add(TFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, -1));

        jLabel6.setText("Apellido");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel7.setText("Dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel8.setText("Rol");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel9.setText("Nombre usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));
        jPanel1.add(TFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 170, -1));
        jPanel1.add(TFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 300, -1));
        jPanel1.add(TFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 300, -1));

        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        jPanel1.add(PFContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 190, -1));

        LbContrasena1.setText("Teléfono");
        jPanel1.add(LbContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        jPanel1.add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        CBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "USUARIO" }));
        jPanel1.add(CBRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPrincipal.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Empleados e = new Empleados();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            
            if (TFDNI.getText().isEmpty() || TFNombre.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No se han cumplimentado todos los campos", "Error campos obligatorios", JOptionPane.WARNING_MESSAGE);
            return;
    }

            // Construir objeto Empleado
            Empleado nuevoEmpleado = new Empleado();
            nuevoEmpleado.setDni(TFDNI.getText());
            nuevoEmpleado.setNombre(TFNombre.getText());
            nuevoEmpleado.setApellidos(TFApellido.getText());
            nuevoEmpleado.setDireccion(TFDireccion.getText());
            nuevoEmpleado.setRol(String.valueOf(CBRol.getSelectedItem()));
            nuevoEmpleado.setNombreUsuario(TFUsuario.getText());
            nuevoEmpleado.setEmail(TFEmail.getText());
            nuevoEmpleado.setTelefono(TFTelefono.getText());
            BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
            String password = String.valueOf(PFContrasena.getPassword());
            
            // Codificar la contraseña
            String encodedPassword = passwordEncoder.encode(password);
            // Guardarla en el empleado
            nuevoEmpleado.setContrasenaHash(encodedPassword);
            

            // Serializar a JSON
            String json = new Gson().toJson(nuevoEmpleado);

            // Crear conexión HTTP
            URL url = new URL("http://localhost:8080/empleado/insert");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setDoOutput(true);
            con.setRequestProperty("Content-Type", "application/json");

            // Enviar datos al servidor
            try (OutputStream os = con.getOutputStream()) {
                byte[] input = json.getBytes("utf-8");
                os.write(input, 0, input.length);
            }

            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                JOptionPane.showMessageDialog(this, "Empleado insertado correctamente");
                Empleados emp = new Empleados();
                emp.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al insertar el empleado");
            }

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBRol;
    private javax.swing.JLabel LbContrasena;
    private javax.swing.JLabel LbContrasena1;
    private javax.swing.JPasswordField PFContrasena;
    private javax.swing.JTextField TFApellido;
    private javax.swing.JTextField TFDNI;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
