/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.google.gson.Gson;
import java.awt.Color;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import models.Empleado;
import utils.Utils;

/**
 * Ventana de modificación de datos de un empleado existente.
 *
 * Esta clase permite al usuario editar los datos personales y de acceso de un
 * empleado. Incluye validaciones para todos los campos y, si los datos son
 * correctos, los envía al backend mediante una petición HTTP PUT en formato
 * JSON.
 *
 * Además, permite cancelar la operación y volver a la vista principal de
 * empleados.
 *
 * @author Lucía Rodríguez Martín
 * @version 1.0
 */
public class ModificarEmpleado extends javax.swing.JFrame {

    private Empleado empleado;

    public ModificarEmpleado(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        this.setLocationRelativeTo(null);
        rellenarDatosEmpleado();
    }

    /**
     * Carga los datos actuales del empleado en los campos del formulario.
     */
    private void rellenarDatosEmpleado() {
        nombre.setText(empleado.getNombre());
        telefono.setText(empleado.getTelefono());
        dni.setText(empleado.getDni());
        apellido.setText(empleado.getApellidos());
        rol.setSelectedItem(empleado.getRol());
        direccion.setText(empleado.getDireccion());
        usuario.setText(empleado.getNombreUsuario());
        mail.setText(empleado.getEmail());
        contrasena.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        LbContrasena = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Didot", 1, 36)); // NOI18N
        jLabel2.setText("Modificar Empleado");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel3.setText("DNI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        dni.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, -1));

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        nombre.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, -1));

        telefono.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, -1));

        apellido.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 290, -1));

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel6.setText("Apellido");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel7.setText("Teléfono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        cancelar.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        modificar.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        modificar.setText("Guardar cambios");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        direccion.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, -1));

        jLabel10.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel10.setText("Dirección");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel8.setText("Rol");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        rol.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "USUARIO" }));
        jPanel1.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 230, -1));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel9.setText("Nombre usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        usuario.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 300, -1));

        jLabel11.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        mail.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, -1));

        LbContrasena.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        LbContrasena.setText("Contraseña");
        jPanel1.add(LbContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        contrasena.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jPanel1.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción que se ejecuta al pulsar el botón "Guardar cambios".
     *
     * Valida todos los campos del formulario y, si son correctos, actualiza el
     * objeto {@link Empleado}, lo serializa a JSON y lo envía al backend
     * mediante una petición PUT. Muestra mensajes de error o éxito según la
     * respuesta del servidor.
     *
     * @param evt Evento de acción del botón
     */
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        try {
            int error = 0;
            Border bordeRojo = BorderFactory.createLineBorder(Color.red, 1);
            Border bordeNormal = BorderFactory.createLineBorder(Color.gray, 1);

            //Comprobar los datos que sean correctos
            if (dni.getText().equals("") || !Utils.validarDNI(dni.getText())) {
                dni.setBorder(bordeRojo);
                error++;
            } else {
                dni.setBorder(bordeNormal);
            }

            if (nombre.getText().equals("")) {
                nombre.setBorder(bordeRojo);
                error++;
            } else {
                nombre.setBorder(bordeNormal);
            }

            if (apellido.getText().equals("")) {
                apellido.setBorder(bordeRojo);
                error++;
            } else {
                apellido.setBorder(bordeNormal);
            }

            if (telefono.getText().equals("")) {
                telefono.setBorder(bordeRojo);
                error++;
            } else {
                telefono.setBorder(bordeNormal);
            }

            if (direccion.getText().equals("")) {
                direccion.setBorder(bordeRojo);
                error++;
            } else {
                direccion.setBorder(bordeNormal);
            }

            if (usuario.getText().equals("")) {
                usuario.setBorder(bordeRojo);
                error++;
            } else {
                usuario.setBorder(bordeNormal);
            }

            if (mail.getText().equals("") || !Utils.validarEmail(mail.getText())) {
                mail.setBorder(bordeRojo);
                error++;
            } else {
                mail.setBorder(bordeNormal);
            }

            if (String.valueOf(contrasena.getPassword()).equals("")) {
                contrasena.setBorder(bordeRojo);
                error++;
            } else {
                if (String.valueOf(contrasena.getPassword()).length() >= 6
                        && String.valueOf(contrasena.getPassword()).length() <= 10
                        && Utils.validarContrasena(String.valueOf(contrasena.getPassword()))) {
                    contrasena.setBorder(bordeNormal);

                } else {
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener entre 6 y 10 carácteres y contener carácteres especiales y mayúsculas");
                    error++;
                }
            }

            //Si no hay errores
            if (error == 0) {

                // Actualizamos los datos del empleado
                empleado.setNombre(nombre.getText());
                empleado.setApellidos(apellido.getText());
                empleado.setDni(dni.getText());
                empleado.setEmail(mail.getText());
                empleado.setNombreUsuario(usuario.getText());
                empleado.setTelefono(telefono.getText());
                empleado.setDireccion(direccion.getText());
                empleado.setRol(rol.getSelectedItem().toString());

                String nuevaContrasena = String.valueOf(contrasena.getPassword());
                if (!nuevaContrasena.isEmpty()) {
                    empleado.setContrasenaHash(nuevaContrasena); // Luego el back hasheará esto
                }

                // Serializar a JSON
                String json = new Gson().toJson(empleado);

                // Enviar al backend
                URL url = new URL("http://localhost:8080/empleado/update");
                HttpURLConnection con = (HttpURLConnection) url.openConnection();
                con.setRequestMethod("PUT");
                con.setRequestProperty("Content-Type", "application/json");
                con.setDoOutput(true);

                try (OutputStream os = con.getOutputStream()) {
                    byte[] input = json.getBytes("utf-8");
                    os.write(input, 0, input.length);
                }

                int responseCode = con.getResponseCode();
                if (responseCode == HttpURLConnection.HTTP_OK) {
                    JOptionPane.showMessageDialog(this, "Empleado modificado correctamente");
                    Empleados vistaEmpleados = new Empleados();
                    vistaEmpleados.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al modificar el empleado. Código: " + responseCode);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en la operación: " + e.getMessage());
        }
    }//GEN-LAST:event_modificarActionPerformed
    /**
     * Acción que se ejecuta al pulsar el botón "Cancelar".
     *
     * Cierra esta ventana y vuelve a la vista de gestión de empleados sin
     * guardar cambios.
     *
     * @param evt Evento de acción del botón
     */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed

        // Vuelve a la ventana de gestión de empleados
        Empleados empleados = new Empleados();
        empleados.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbContrasena;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton cancelar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
