/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

public class VerActividades extends javax.swing.JFrame {

    /**
     * Creates new form GestionActividades
     */
    public VerActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        verActividad = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        insertarActividad = new javax.swing.JButton();
        eliminarActividad1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Actividades");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Empleado", "Horario disponible"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 720, 190));

        verActividad.setText("Ver actividad");
        verActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActividadActionPerformed(evt);
            }
        });
        jPanel1.add(verActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        insertarActividad.setText("Añadir actividad");
        insertarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActividadActionPerformed(evt);
            }
        });
        jPanel1.add(insertarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        eliminarActividad1.setText("Eliminar actividad");
        eliminarActividad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActividad1ActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarActividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActividadActionPerformed
        GestionActividades act = new GestionActividades(false);
        act.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verActividadActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void insertarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActividadActionPerformed
        // TODO add your handling code here:
        GestionActividades act = new GestionActividades(true);
        act.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_insertarActividadActionPerformed

    private void eliminarActividad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActividad1ActionPerformed

    }//GEN-LAST:event_eliminarActividad1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton eliminarActividad1;
    private javax.swing.JButton insertarActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton verActividad;
    // End of variables declaration//GEN-END:variables
}
